spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=producttdb;encrypt=false
    username: user
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
